[package]
name = "logsh"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.3.22", features = ["derive"] }
serde = { version = "1.0.183", features = ["derive"] }
serde_json = { version = "1.0", features = ["raw_value"] }
log = { version = "0.4.20" }
reqwest = { version = "0.11", features = ["blocking", "json"] }
home = "0.5.5"
term-table = "1.3.2"
uuid = "1.4.1"
thiserror = "1.0.47"
csv = "1.2.2"
pretty_env_logger = "0.5.0"
