on:
  push:
    tags: ['v*.*.*']
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: Logsh CLI Build and Release

jobs:
  build:
    strategy:
      matrix:
        include:
          # Linux builds
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            arch: x86_64
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            arch: aarch64
          - os: ubuntu-latest
            target: armv7-unknown-linux-gnueabihf
            arch: armv7
          # macOS builds
          - os: macos-latest
            target: x86_64-apple-darwin
            arch: x86_64
          - os: macos-latest
            target: aarch64-apple-darwin
            arch: aarch64
          # Windows builds
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            arch: x86_64
          - os: windows-latest
            target: aarch64-pc-windows-msvc
            arch: aarch64
    name: Build and Package (${{ matrix.target }})
    runs-on: ${{ matrix.os }}
    env:
      PROJECT_NAME_UNDERSCORE: logsh
    steps:
      - uses: actions/checkout@v4

      - name: Inject Tag Version
        if: startsWith(github.ref, 'refs/tags/v')
        shell: pwsh
        run: |
          $Env:GIT_VERSION = $Env:GITHUB_REF -replace 'refs/.*/v', ''
          (Get-Content ./logsh/Cargo.toml) -replace '^version\s+=\s+"([0-9\.]+)"\s*$', "version = `"$($Env:GIT_VERSION)`"" | Out-File ./logsh/Cargo.toml
          echo "Version should be $($Env:GIT_VERSION)"
          echo "----------------------------------------"
          cat ./logsh/Cargo.toml

      - name: Install system dependencies (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libssl-dev pkg-config

      - name: Install system dependencies (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          brew install openssl
          echo "OPENSSL_ROOT_DIR=$(brew --prefix openssl)" >> $GITHUB_ENV

      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: ${{ matrix.target }}
      
      - name: Install cross-compilation tool
        if: matrix.target != 'x86_64-unknown-linux-gnu' && matrix.os == 'ubuntu-latest'
        run: |
          cargo install cross --git https://github.com/cross-rs/cross
      
      - name: Release Build (Cross-compilation)
        if: matrix.target != 'x86_64-unknown-linux-gnu' && matrix.os == 'ubuntu-latest'
        run: cross build --release --target ${{ matrix.target }}
        working-directory: ./logsh
        env:
          CROSS_CONTAINER_IN_CONTAINER: true
      
      - name: Release Build (Native)
        if: matrix.target == 'x86_64-unknown-linux-gnu' || matrix.os != 'ubuntu-latest'
        run: cargo build --release --target ${{ matrix.target }}
        working-directory: ./logsh
      
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: logsh-cli-${{ matrix.target }}
          path: |
            logsh/target/${{ matrix.target }}/release/${{ env.PROJECT_NAME_UNDERSCORE }}
            logsh/target/${{ matrix.target }}/release/${{ env.PROJECT_NAME_UNDERSCORE }}.exe

  prerelease:
    name: Create pre-release
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
      
      - name: Create pre-release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest-pre"
          prerelease: true
          title: "Development Build"
          files: |
            artifacts/**/*

  release:
    name: Create release
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
      
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: artifacts/**/*
          generate_release_notes: true