on:
  push:
    tags: ['v*.*.*']
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: Logsh CLI Build and Release

jobs:
  build:
    strategy:
      matrix:
        include:
          # Linux x86_64
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          # macOS Intel
          - os: macos-13
            target: x86_64-apple-darwin
          # macOS Apple Silicon
          - os: macos-latest
            target: aarch64-apple-darwin
          # Windows x86_64
          - os: windows-latest
            target: x86_64-pc-windows-msvc
    name: Build and Package (${{ matrix.target }})
    runs-on: ${{ matrix.os }}
    env:
      PROJECT_NAME_UNDERSCORE: logsh
    steps:
      - uses: actions/checkout@v4

      - name: Inject Tag Version
        if: startsWith(github.ref, 'refs/tags/v')
        shell: pwsh
        run: |
          $Env:GIT_VERSION = $Env:GITHUB_REF -replace 'refs/.*/v', ''
          (Get-Content ./logsh/Cargo.toml) -replace '^version\s+=\s+"([0-9\.]+)"\s*$', "version = `"$($Env:GIT_VERSION)`"" | Out-File ./logsh/Cargo.toml
          echo "Version should be $($Env:GIT_VERSION)"
          echo "----------------------------------------"
          cat ./logsh/Cargo.toml

      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: ${{ matrix.target }}
      
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: logsh
          key: ${{ matrix.target }}
          cache-all-crates: true
      
      - name: Build
        run: cargo build --release --target ${{ matrix.target }}
        working-directory: ./logsh
      
      - name: Prepare artifacts
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Path artifacts -Force
          if ("${{ matrix.os }}" -eq "windows-latest") {
            $binaryPath = "logsh/target/${{ matrix.target }}/release/logsh.exe"
          } else {
            $binaryPath = "logsh/target/${{ matrix.target }}/release/logsh"
          }
          $zipPath = "artifacts/logsh-${{ matrix.target }}.zip"
          Compress-Archive -Path $binaryPath -DestinationPath $zipPath
      
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: logsh-cli-${{ matrix.target }}
          path: artifacts/

  prerelease:
    name: Create pre-release
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
      
      - name: Create pre-release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest-pre"
          prerelease: true
          title: "Development Build"
          files: |
            artifacts/**/*

  container:
    name: Build and Push Docker Image
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=raw,value=latest,enable={{is_default_branch}}
            type=raw,value=latest-pre,enable=${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master' }}

      - name: Inject Tag Version
        if: startsWith(github.ref, 'refs/tags/v')
        shell: pwsh
        run: |
          $Env:GIT_VERSION = $Env:GITHUB_REF -replace 'refs/.*/v', ''
          (Get-Content ./logsh/Cargo.toml) -replace '^version\s+=\s+"([0-9\.]+)"\s*$', "version = `"$($Env:GIT_VERSION)`"" | Out-File ./logsh/Cargo.toml
          echo "Version should be $($Env:GIT_VERSION)"
          echo "----------------------------------------"
          cat ./logsh/Cargo.toml
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  release:
    name: Create release
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
      
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: artifacts/**/*
          generate_release_notes: true